version: 2
models:
  - name: algorand__application_call_transaction
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - block_id
            - INTRA
    columns:
      - name: BLOCK_TIMESTAMP
        tests:
          - not_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: hour
              interval: 50
      - name: block_id
        tests:
          - not_null
      - name: INTRA
        tests:
          - not_null
      - name: TX_ID
        tests:
          - not_null
      - name: INNER_TX
        tests:
          - not_null
      - name: SENDER
        tests:
          - not_null
      - name: FEE
        tests:
          - not_null:
              where: inner_tx = 'true'
      - name: TX_TYPE
        tests:
          - not_null
      - name: TX_TYPE_NAME
        tests:
          - not_null
      - name: GENESIS_HASH
        tests:
          - not_null
      - name: TX_MESSAGE
        tests:
          - not_null
