version: 2
models:
  - name: algorand__asset_configuration_transaction
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - BLOCK_ID
            - INTRA
    columns:
      - name: BLOCK_TIMESTAMP
        description: "{{ doc('block_timestamp') }}"
        tests:
          - dbt_expectations.expect_column_to_exist   
      - name: BLOCK_ID
        description: "{{ doc('algo_block_id') }}"
        tests:
          - not_null
      - name: INTRA
        description: "{{ doc('intra') }}"
        tests:
          - not_null
      - name: TX_ID
        description: "{{ doc('tx_id') }}"
        tests:
          - not_null
      - name: INNER_TX
        description: "{{ doc('inner_tx') }}"
        tests:
          - not_null
      - name: ASSET_ID
        description: "{{ doc('algo_asset_id') }}"
        tests:
          - not_null:
              where: inner_tx = 'false'
      - name: ASSET_SUPPLY
        description: "The total number of base units of the asset to create. This number cannot be changed."
        tests:
          - dbt_expectations.expect_column_to_exist 
      - name: SENDER
        description: "{{ doc('sender') }}"
        tests:
          - not_null   
      - name: FEE
        description: "{{ doc('fee') }}"
        tests:
          - not_null:
              where: inner_tx = 'true'     
      - name: ASSET_PARAMETERS
        description: "All parameters involved with the asset being created, modified or destroyed in the transaction"
        tests:
          - dbt_expectations.expect_column_to_exist  
      - name: TX_TYPE
        description: "{{ doc('tx_type') }}"
        tests:
          - not_null
      - name: TX_TYPE_NAME
        description: "{{ doc('tx_type_name') }}"
        tests:
          - not_null
      - name: GENESIS_HASH
        description: "{{ doc('genesis_hash') }}"
        tests:
          - not_null          
      - name: TX_MESSAGE
        description: "{{ doc('tx_message') }}"
        tests:
          - not_null