name: 'dbt_date'
version: '0.4'

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

require-dbt-version: [">=0.20.0", "<1.1.0"]
profile: integration_tests

quoting:
    identifier: false
    schema: false

vars:
    'dbt_date:time_zone': 'America/Los_Angeles'

