version: 2

models:
  - name: ethereum__dex_swaps
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - TX_ID
            - DIRECTION
            - EVENT_INDEX
    columns:
      - name: TX_ID
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "0[xX][0-9a-fA-F]+"
      - name: DIRECTION
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["IN", "OUT"]
      - name: EVENT_INDEX
        tests:
          - not_null

      - name: AMOUNT_IN
        tests:
          - dbt_expectations.expect_column_values_to_be_in_type_list:
              column_type_list: [decimal, float]
      - name: AMOUNT_OUT
        tests:
          - dbt_expectations.expect_column_values_to_be_in_type_list:
              column_type_list: [decimal, float]
      - name: AMOUNT_USD
        tests:
          - dbt_expectations.expect_column_values_to_be_in_type_list:
              column_type_list: [decimal, float]
      - name: BLOCK_TIMESTAMP
        tests:
          - not_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1
      - name: FROM_ADDRESS
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "0[xX][0-9a-fA-F]+"
      - name: PLATFORM
        tests:
          - not_null
      - name: POOL_ADDRESS
        tests:
          - not_null
      - name: POOL_NAME
        tests:
          - not_null
      - name: TOKEN_ADDRESS
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "0[xX][0-9a-fA-F]+"
      - name: TO_ADDRESS
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "0[xX][0-9a-fA-F]+"

  - name: ethereum__dex_liquidity_pools
    columns:
      - name: POOL_ADDRESS
        tests:
          - unique
          - not_null
      - name: CREATION_TIME
        tests:
          - not_null
      - name: CREATION_TX
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "0[xX][0-9a-fA-F]+"
      - name: FACTORY_ADDRESS
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "0[xX][0-9a-fA-F]+"
      - name: PLATFORM
        tests:
          - not_null
      - name: TOKEN0
        tests:
          - not_null
      - name: POOL_NAME
        tests:
          - not_null
      - name: TOKEN1
        tests:
          - not_null
