version: 2

models:
  - name: ethereum__dex_swaps
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - tx_id
            - direction
            - event_index
    columns:
      - name: tx_id
        tests:
          - not_null
      - name: direction
        tests:
          - not_null
      - name: event_index
        tests:
          - not_null
  - name: ethereum__dex_liquidity_pools
    columns:
      - name: POOL_ADDRESS
        tests:
          - unique
          - not_null
      - name: CREATION_TIME
        tests:
          - not_null
      - name: CREATION_TX
        tests:
          - not_null
      - name: FACTORY_ADDRESS
        tests:
          - not_null
      - name: PLATFORM
        tests:
          - not_null
      - name: TOKEN0
        tests:
          - not_null
      - name: POOL_NAME
        tests:
          - not_null
      - name: TOKEN1
        tests:
          - not_null
