version: 2

models:
  - name: silver_polygon__events_emitted
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - CHAIN_ID
            - BLOCK_ID
            - TX_ID
            - EVENT_INDEX
    columns:
      - name: BLOCK_ID
        tests:
          - not_null
      - name: CHAIN_ID
        tests:
          - not_null
      - name: EVENT_INDEX
        tests:
          - not_null

      - name: BLOCK_TIMESTAMP
        tests:
          - not_null
      - name: CONTRACT_ADDRESS
        tests:
          - not_null
      - name: TX_ID
        tests:
          - not_null
      - name: CONTRACT_NAME
        tests:
      - name: EVENT_INPUTS
        tests:
        # TODO: null_where
      - name: EVENT_NAME
        tests:
          - not_null
      - name: EVENT_REMOVED
        tests:
          - not_null
      - name: SYSTEM_CREATED_AT
        tests:
          - not_null
      - name: TX_FROM
        tests:
          - not_null
      - name: TX_SUCCEEDED
        tests:
          - not_null
      - name: TX_TO
        tests:
        # TODO: null_where

  - name: silver_polygon__transactions
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - CHAIN_ID
            - BLOCK_ID
            - TX_ID
    columns:
      - name: BLOCK_ID
        tests:
          - not_null
      - name: CHAIN_ID
        tests:
          - not_null
      - name: TX_ID
        tests:
          - not_null

      - name: BLOCK_TIMESTAMP
        tests:
          - not_null
      - name: FEE
        tests:
          - not_null
      - name: FROM_ADDRESS
        tests:
          - not_null
      - name: GAS_LIMIT
        tests:
          - not_null
      - name: GAS_PRICE
        tests:
          - not_null
      - name: GAS_USED
        tests:
          - not_null
      - name: INPUT_METHOD
        tests:
          - not_null
      - name: NATIVE_VALUE
        tests:
          - not_null
      - name: NONCE
        tests:
          - not_null
      - name: SUCCESS
        tests:
          - not_null
      - name: SYSTEM_CREATED_AT
        tests:
          - not_null
      - name: TO_ADDRESS
        tests:
        # TODO: null_where
      - name: TX_POSITION
        tests:
          - not_null

  - name: silver_polygon__udm_events
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - BLOCK_ID
            - CHAIN_ID
            - LOG_INDEX
            - TX_ID
    columns:
      - name: BLOCK_ID
        tests:
          - not_null
      - name: CHAIN_ID
        tests:
          - not_null
      - name: LOG_INDEX
        tests:
          - not_null
      - name: TX_ID
        tests:
          - not_null

      - name: BLOCK_TIMESTAMP
        tests:
          - not_null
      - name: CONTRACT_ADDRESS
        tests:
          # TOOD: null_where
      - name: FEE
        tests:
          - not_null
      - name: FROM_ADDRESS
        tests:
          - not_null
      - name: INPUT_METHOD
        tests:
          - not_null
      - name: LOG_METHOD
        tests:
          - not_null
      - name: NAME
        tests:
      - name: NATIVE_VALUE
        tests:
          - not_null
      - name: SYMBOL
        tests:
      - name: SYSTEM_CREATED_AT
        tests:
          - not_null
      - name: TOKEN_VALUE
        tests:
          - not_null
      - name: TO_ADDRESS
        tests:
        # TODO: null_where
