version: 2

sources:
  - name: shared
    schema: silver
    tables:
      - name: prices
      - name: prices_v2
      - name: cmc_assets
      - name: market_asset_metadata
      - name: coingecko_prices
      - name: hours
      - name: udm_address_labels
      - name: udm_address_tags
      - name: udm_balances
      - name: udm_decimal_adjustments
      - name: udm_velocity
  - name: ethereum
    schema: silver
    tables:      
      - name: ethereum_contracts
      - name: daily_ethereum_token_balances
      - name: ethereum_address_labels
      - name: ethereum_address_labels_updates
      - name: ethereum_contract_decimal_adjustments
      - name: ethereum_decoded_log_methods
      - name: ethereum_events
      - name: ethereum_events_emitted
      - name: ethereum_reads
      - name: ethereum_transactions
      - name: ethereum_token_balances
      - name: ethereum_token_contracts
      - name: sha256_function_signatures
      - name: nft_metadata
  - name: flow
    schema: silver
    tables:
      - name: daily_flow_staked_balances
      - name: udm_daily_balances_flow
      - name: udm_events_flow
  - name: uniswapv3_eth
    schema: silver
    tables:
      - name: rinkeby_uniswapv3_liquidity_actions
      - name: rinkeby_uniswapv3_pools
      - name: rinkeby_uniswapv3_pool_stats
      - name: rinkeby_uniswapv3_positions
      - name: rinkeby_uniswapv3_swaps
      - name: uniswapv3_liquidity_actions
      - name: uniswapv3_pools
      - name: uniswapv3_pool_stats
      - name: uniswapv3_positions
      - name: uniswapv3_swaps
  - name: ethereum_nondbt
    schema: ethereum
    tables:      
      - name: token_prices_hourly_v2
  - name: thorchain_midgard
    schema: thorchain_midgard_public
    tables:
      - name: active_vault_events
      - name: add_events
      - name: asgard_fund_yggdrasil_events
      - name: block_pool_depths
      - name: block_log
      - name: bond_events
      - name: constants
      - name: errata_events
      - name: fee_events
      - name: gas_events
      - name: inactive_vault_events
      - name: message_events
      - name: new_node_events
      - name: outbound_events
      - name: pending_liquidity_events
      - name: pool_balance_change_events
      - name: pool_events
      - name: refund_events
      - name: reserve_events
      - name: rewards_events
      - name: rewards_event_entries
      - name: set_ip_address_events
      - name: set_mimir_events
      - name: set_node_keys_events
      - name: set_version_events
      - name: slash_amounts
      - name: stake_events
      - name: swap_events
      - name: switch_events
      - name: transfer_events
      - name: unstake_events
      - name: update_node_account_status_events
      - name: validator_request_leave_events
  - name: terra
    schema: silver
    tables:
      - name: terra_blocks
      - name: terra_transitions
      - name: terra_transactions
      - name: terra_msgs
      - name: terra_msg_events
      - name: terra_validator_voting_power
