version: 2

sources:
  - name: shared
    schema: silver
    tables:
      - name: prices
      - name: prices_v2
      - name: cmc_assets
      - name: market_asset_metadata
      - name: coingecko_prices
      - name: hours
      - name: udm_address_labels
      - name: udm_address_labels_new
      - name: udm_address_tags
      - name: udm_balances
      - name: udm_decimal_adjustments
      - name: udm_velocity
      - name: uniswapv2factory_event_paircreated
      - name: flow_balances
      - name: near_balances
      - name: algorand_balances
      - name: terra_balances
  - name: ethereum
    schema: silver
    tables:
      - name: ethereum_balances
      - name: ethereum_contracts
      - name: daily_ethereum_token_balances
      - name: ethereum_address_labels
      - name: ethereum_address_labels_updates
      - name: ethereum_contract_decimal_adjustments
      - name: ethereum_decoded_log_methods
      - name: ethereum_events
      - name: ethereum_events_emitted
      - name: ethereum_proxy_contract_registry
      - name: ethereum_reads
      - name: ethereum_transactions
      - name: ethereum_token_balances
      - name: ethereum_token_contracts
      - name: sha256_function_signatures
      - name: nft_metadata
  - name: flow
    schema: silver
    tables:
      - name: daily_flow_staked_balances
      - name: udm_daily_balances_flow
      - name: udm_events_flow
  - name: uniswapv3_eth
    schema: silver
    tables:
      - name: rinkeby_uniswapv3_liquidity_actions
      - name: rinkeby_uniswapv3_pools
      - name: rinkeby_uniswapv3_pool_stats
      - name: rinkeby_uniswapv3_positions
      - name: rinkeby_uniswapv3_swaps
      - name: uniswapv3_liquidity_actions
      - name: uniswapv3_pools
      - name: uniswapv3_pool_stats
      - name: uniswapv3_positions
      - name: uniswapv3_swaps
  - name: ethereum_nondbt
    schema: ethereum
    tables:
      - name: token_prices_hourly_v2
  - name: thorchain_midgard
    schema: thorchain_midgard_public
    tables:
      - name: active_vault_events
      - name: add_events
      - name: asgard_fund_yggdrasil_events
      - name: block_pool_depths
      - name: block_log
      - name: bond_events
      - name: constants
      - name: errata_events
      - name: fee_events
      - name: gas_events
      - name: inactive_vault_events
      - name: message_events
      - name: new_node_events
      - name: outbound_events
      - name: pending_liquidity_events
      - name: pool_balance_change_events
      - name: pool_events
      - name: refund_events
      - name: reserve_events
      - name: rewards_events
      - name: rewards_event_entries
      - name: set_ip_address_events
      - name: set_mimir_events
      - name: set_node_keys_events
      - name: set_version_events
      - name: slash_amounts
      - name: stake_events
      - name: swap_events
      - name: switch_events
      - name: transfer_events
      - name: unstake_events
      - name: update_node_account_status_events
      - name: validator_request_leave_events
  - name: terra
    schema: silver
    tables:
      - name: udm_daily_balances_terra
      - name: terra_validator_voting_power
      - name: udm_custom_fields_terra_tax_rate # TODO: drop table as it is not being referenced in dbt anymore.
  - name: bronze
    schema: bronze
    tables:
      - name: prod_matic_sink_510901820
      - name: prod_terra_sink_645110886
      - name: prod_address_label_sink_291098491
      - name: prod_ethereum_sink_407559501
      - name: JIM_TEST_REST_PROXY_1507016047
  - name: gold
    schema: gold
    tables:
      - name: flow_daily_balances
  - name: crosschain
    schema: silver_crosschain
    tables:
      - name: address_labels
  - name: near
    schema: redshift
    tables:
      - name: near_validators
      - name: near_daily_reward_flow
      - name: near_delegator_counts
      - name: udm_events_near
  - name: near_silver
    schema: silver_near
    tables:
      - name: daily_balances
